name: 📝 Documentation Update
description: Improve or fix project documentation
title: "[DOCS] <short title>"
labels: [documentation]
body:
  - type: input
    id: file
    attributes:
      label: File or Section
      placeholder: "README.md > Installation"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What's wrong or unclear?
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Update
      description: What should be added or changed?
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links, examples, or screenshots.
