name: ✨ Feature Request
description: Suggest an idea or enhancement
title: "[FEATURE] <short title>"
labels: [enhancement, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        Help us understand your idea clearly.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      placeholder: "Add dark mode toggle in settings"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - 🔴 Critical - Needed immediately
        - 🟠 High - Strongly improves user experience
        - 🟡 Medium - Nice-to-have
        - 🟢 Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem will this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how it should work.
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: References, links, or designs.
